# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa7af731e0513576ffb23382cd4484b9201bf898812e240bfacb9af5bfa06712c9014c151429c00b7aa23f979e9152c1914bac921aa2dd8696c1c5aa0ec2fc08

test:
  secret_key_base: b71c86a6d1a24609144ecc2af499b9a093ce2fe20982359301299869dc305aa821cedb293af03daa78729bd9f8a1a9a96b360517c10fb5ad523ee3606559084a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
